"""Rename date to price in Investment model

Revision ID: e2b2e4513c5b
Revises: 
Create Date: 2025-01-25 15:07:55.066933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b2e4513c5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment', schema=None) as batch_op:
        batch_op.alter_column('date', new_column_name='price', existing_type=sa.Float, nullable=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment', schema=None) as batch_op:
        batch_op.alter_column('price', new_column_name='date', existing_type=sa.Float, nullable=False)
    # ### end Alembic commands ###